language: python
dist: bionic
python:
- '3.6'
node_js:
- '8'
cache:
  pip: true
  npm: true
install:
- npm install
- npm run build
- pip install -r requirements/dev.txt
- pip install coveralls
script:
- python manage.py collectstatic > /dev/null
- py.test --cov
- python manage.py makemigrations --dry-run --check --noinput
after_success:
- coveralls
deploy:
- provider: script
  script: scripts/deploy.sh
  on:
    branch: master
env:
  global:
    secure: "BgcjSJaqzSA82MHAXC9MDk43s7vb6dT6J9algjdMW+3NHDMejoHj0k+wtifeQiaVR1Rbm/g+Kf9yzfh15qj9u+Pv8nz4dFuCYmPZrbonvuEilrPzKeykv/2oTIT8JOEQTyg3S/j4Kcfn8emvISmNftFIsyURbGMI1CGA/petUIqOXHZno4/9uwBlW8jyO424WGLVdMHlUa2V74K5Nf2xsWaiIWIcdTLxsVmV+pXAbgWJnHqb+ohWPKhwrmJmpE/IZP3UZs//V6ncQsVRLlTBRdJXIjQICSeRvEkRJ+LELACvAaNDSPK2rrNygKLgJOnHAVMPCIVU8ot8qf8NyPbLjbnHT4KhJMpgchstBN0O+/HkYb/9XnPyGiccnzUie71s5xxCCVVniPPNkdFuAjV6Aiz3/+29h/jXbs5yAMFviaYFFgQ4lGgdGjGPKk1VoJQ3o/lygNJ+pm+3wXv3wT0+vBqA3J1baoNn1ekFcvDW78QTU2O/VxrzftL8nESTkRLntNStxfFE3GNAChUo0/egYB4VkwjGjgNZCUkhopnFJx53jSXYUjprpCNAtylRzE015BXIBScPE+xIujpgx6ctgZdtRDLZJPexRXy0BfjsTHMSfrovHRI09/cYMI5cfvPUeSSjVNdnVzRig4iuRMwS51d/v2i8vDWed+OqeE7ih2k="
