# Generated by Django 2.2.7 on 2020-01-08 16:29

import adhocracy4.images.fields
import apps.ideas.countries
import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a4modules', '0004_description_maxlength_512'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='a4modules.Item')),
                ('first_name', models.CharField(help_text='Your first name and last name will be published together with the proposal.', max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('organisation_status', models.CharField(choices=[('non_profit', 'I am applying on behalf of a registered non-profit organisation, e.g. NGO'), ('non_profit_planned', 'Registration as a non-profit organisation is planned or is already underway'), ('no_non_profit', 'I have a really good idea, but will need help to register a non-profit organisation'), ('other', 'Other')], max_length=255)),
                ('organisation_status_extra', models.TextField(blank=True, help_text='Please provide details about your current status, especially if you selected "Other" (max. 200 characters)', max_length=200, verbose_name='Organisation details')),
                ('organisation_name', models.CharField(blank=True, help_text='If you do not yet have a registered organisation, please write the name of your initiative or planned  organisation here.', max_length=300)),
                ('organisation_website', models.URLField(blank=True, max_length=500)),
                ('organisation_country', django_countries.fields.CountryField(blank=True, countries=apps.ideas.countries.EuropeanCountries, max_length=2)),
                ('organisation_city', models.CharField(blank=True, max_length=250)),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Organisation email')),
                ('year_of_registration', models.IntegerField(blank=True, null=True)),
                ('reach_out', models.TextField(blank=True, help_text='What kind of advice, comments or feedback would you like to receive about your idea from others on the platform? (max. 300 characters)', max_length=300, verbose_name='Reach out – get feedback, ideas and inspiration from the Civic Europe online Community!')),
                ('how_did_you_hear', models.CharField(choices=[('personal_contact', 'Personal contact'), ('websites', 'Website'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('newsletter', 'Newsletter'), ('other', 'Other')], max_length=255, verbose_name='How did you hear about Civic Europe?')),
                ('idea_title', models.CharField(help_text='Give your idea a short and meaningful title. (max. 50 characters)', max_length=50)),
                ('idea_subtitle', models.CharField(blank=True, help_text='(max. 200 characters)', max_length=200)),
                ('idea_pitch', models.TextField(help_text='Present your idea in max. 500 characters. Share a concise and appealing text that makes the reader curious. Try to pitch your main challenge, objective, method and target group in 3-5 sentences.', max_length=500)),
                ('idea_image', adhocracy4.images.fields.ConfiguredImageField('idea_image', blank=True, help_text='Upload a photo or illustration that visually supports or explains your idea. Make sure that you have the property rights to share this picture. You can upload a .jpg, .png or .gif of up to 3 MB in size. The image should be in landscape (not portrait) format and have a width of at least 400 pixels.', upload_to='ideas/images', verbose_name='Visualise your idea')),
                ('idea_topics', multiselectfield.db.fields.MultiSelectField(choices=[('democracy_participation', 'Democracy and participation'), ('arts_cultural_activities', 'Arts and cultural activities'), ('environment', 'Environment'), ('social_inclusion', 'Social inclusion'), ('migration', 'Migration'), ('communities', 'Communities'), ('urban_development', 'Urban development'), ('education', 'Education')], help_text='Choose 1-2 topics that describe your idea. Your answer to this question does not influence the selection process. It helps us to get a better overview of the proposals we receive.', max_length=255, verbose_name='Topic')),
                ('idea_topics_other', models.CharField(blank=True, help_text='Please specify. (max 250 characters)', max_length=250, verbose_name='Other')),
                ('idea_location', multiselectfield.db.fields.MultiSelectField(choices=[('city', 'City, country or region (please specify below)'), ('online', 'Online'), ('ruhr_linkage', 'Links to the Ruhr area of Germany')], help_text='Where will your idea take place? Choose all options that apply. 1-3 choices possible.', max_length=250, verbose_name='Location')),
                ('idea_location_specify', models.TextField(blank=True, help_text='Please specify the city, country and/or region, e.g. Berlin, Germany. (max. 100 characters)', max_length=100, verbose_name='Location details')),
                ('idea_location_ruhr', models.TextField(blank=True, help_text='Is your project connected to the Ruhr area of Germany through project partners or audiences? Please provide further details. (max. 500 characters)', max_length=500, verbose_name='Links to the Ruhr area')),
                ('challenge', models.TextField(help_text='How does your idea address the challenges of democracy in Europe today? How does it suit our 2017-2018 call for ideas for democracy in Europe? (max. 800 characters)', max_length=800, verbose_name='How will your idea strengthen democracy in Europe?')),
                ('outcome', models.TextField(help_text='If your idea is selected, what will be different a year from now? What will have changed? (max. 800 characters)', max_length=800, verbose_name='What would be a successful outcome for your idea?')),
                ('plan', models.TextField(help_text='Describe as concretely as possible the approach and/or the method you will use when implementing your idea. What are the steps you plan to take? (max. 800 characters)', max_length=800, verbose_name='How do you plan to get there?')),
                ('importance', models.TextField(help_text='What motivates you to bring this idea to life? What is your story? What is your connection and mission behind the idea? (max. 800 characters)', max_length=800, verbose_name='Why is this idea important to you?')),
                ('target_group', models.TextField(help_text='Which target groups, stakeholders, beneficiaries or audiences are at the centre of your idea? (max. 800 characters)', max_length=800, verbose_name='Who are you doing it for and/or with?')),
                ('members', models.TextField(help_text='Please introduce us to the main members of your project team and briefly summarise their experience and skills. (max. 800 characters)', max_length=800, verbose_name='Who is in your project team?')),
                ('partner_organisation_1_name', models.CharField(blank=True, max_length=300, verbose_name='Organisation Name')),
                ('partner_organisation_1_website', models.URLField(blank=True, max_length=500, verbose_name='website')),
                ('partner_organisation_1_country', django_countries.fields.CountryField(blank=True, countries=apps.ideas.countries.EuropeanCountries, max_length=2, verbose_name='country')),
                ('partner_organisation_2_name', models.CharField(blank=True, max_length=300, verbose_name='Organisation Name')),
                ('partner_organisation_2_website', models.URLField(blank=True, max_length=500, verbose_name='website')),
                ('partner_organisation_2_country', django_countries.fields.CountryField(blank=True, countries=apps.ideas.countries.EuropeanCountries, max_length=2, verbose_name='country')),
                ('partner_organisation_3_name', models.CharField(blank=True, max_length=300, verbose_name='Organisation Name')),
                ('partner_organisation_3_website', models.URLField(blank=True, max_length=500, verbose_name='website')),
                ('partner_organisation_3_country', django_countries.fields.CountryField(blank=True, countries=apps.ideas.countries.EuropeanCountries, max_length=2, verbose_name='country')),
                ('partners_more_info', models.TextField(blank=True, help_text='Please use this field if you have more than 3 partner organisations or if you want to tell us more about your proposed partnership arrangements (max. 200 characters).', max_length=200, verbose_name='More information')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='idea_title', unique=True)),
                ('is_on_shortlist', models.BooleanField(default=False)),
                ('is_winner', models.BooleanField(default=False)),
                ('jury_statement', models.TextField(blank=True, verbose_name='Why this idea?')),
                ('community_award_winner', models.BooleanField(default=False)),
                ('budget_granted', models.IntegerField(blank=True, null=True)),
                ('co_workers', models.ManyToManyField(blank=True, related_name='idea_co_workers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
            bases=('a4modules.item', models.Model),
        ),
        migrations.CreateModel(
            name='IdeaSketch',
            fields=[
                ('idea_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='civic_europe_ideas.Idea')),
                ('idea_challenge_camp_represent', models.TextField(help_text='Specify one person only.', max_length=150, verbose_name='Who will represent your idea at the Idea Challenge Camp and why?')),
                ('idea_challenge_camp_benefit', models.TextField(help_text='Tell us about your expectations. Think about your skills, resources, networks and partners when describing what you could offer and what you would like to take away. (max. 300 characters)', max_length=300, verbose_name='How could you contribute to and benefit from participating in the Idea Challenge Camp?')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
            bases=('civic_europe_ideas.idea', models.Model),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('idea_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='civic_europe_ideas.Idea')),
                ('total_budget', models.IntegerField(help_text='Please indicate your overall budget. The total budget may (but does not have to) include the applicant’s own contribution and/or external sources of funding.', verbose_name='Total Budget')),
                ('budget_requested', models.IntegerField(help_text='Funding requested from Civic Europe can range from 1 to 50,000 EUR. Depending on your planning, the amount entered here can be the same as the “total budget” figure entered above.', verbose_name='Funding requested from Civic Europe')),
                ('major_expenses', models.TextField(help_text='Which are the major expenses you foresee for the implementation of your idea? Please share a rough estimate by cost category (e.g. office expenses 1000 EUR, travel and accommodation costs 3000 EUR, public relations 2000 EUR, personnel costs etc.)', max_length=500, verbose_name='Major expenses')),
                ('duration', models.IntegerField(help_text='How many months will it take to implement your project?', verbose_name='Duration of project (number of months)')),
                ('network', models.TextField(help_text='The Civic Europe network includes all previous winning projects, jury members, the online community, the partner organisations Stiftung Mercator, MitOst e.V. and Liquid Democracy e.V. and the Civic Europe team. Winning projects meet at least one time per year in network meetings. Tell us about your expectations. Think about your skills, resources, networks and partners when describing what you could offer and what you would like to take away. (max. 800 characters)', max_length=800, verbose_name='How will you contribute to and benefit from the Civic Europe network?')),
                ('selection_cohesion', models.TextField(blank=True, max_length=500, verbose_name='How will your idea strengthen connection and cohesion in Europe?')),
                ('selection_apart', models.TextField(help_text='What is surprising or unconventional about your idea? What is special about it? (max. 800 characters)', max_length=800, verbose_name='What makes your idea stand apart?')),
                ('selection_relevance', models.TextField(blank=True, help_text='How will your project connect to, or influence, people’s daily lives?', max_length=500, verbose_name='What is the practical relevance of your idea to people’s everyday lives?')),
                ('selection_key_indicators', models.TextField(help_text='What are the key indicators of success of your endeavour in the first year? What are key indicators for failure in the first year? If successful, how will you amplify your successes? If you should fail, how will you recover? (max. 800 characters)', max_length=800, verbose_name='Key Indicators')),
                ('selection_advocating', models.TextField(help_text='Through what actions, measures or channels will you be reaching out to your key target groups and others to whom your idea is relevant? (max. 800 characters)', max_length=800, verbose_name='How will you be reaching out to others and advocating your idea?')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
            bases=('civic_europe_ideas.idea', models.Model),
        ),
        migrations.CreateModel(
            name='IdeaSketchArchived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False, null=True)),
                ('first_name', models.CharField(help_text='Your first name and last name will be published together with the proposal.', max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('organisation_status', models.CharField(choices=[('non_profit', 'I am applying on behalf of a registered non-profit organisation, e.g. NGO'), ('non_profit_planned', 'Registration as a non-profit organisation is planned or is already underway'), ('no_non_profit', 'I have a really good idea, but will need help to register a non-profit organisation'), ('other', 'Other')], max_length=255)),
                ('organisation_status_extra', models.TextField(blank=True, help_text='Please provide details about your current status, especially if you selected "Other" (max. 200 characters)', max_length=200, verbose_name='Organisation details')),
                ('organisation_name', models.CharField(blank=True, help_text='If you do not yet have a registered organisation, please write the name of your initiative or planned  organisation here.', max_length=300)),
                ('organisation_website', models.URLField(blank=True, max_length=500)),
                ('organisation_country', django_countries.fields.CountryField(blank=True, countries=apps.ideas.countries.EuropeanCountries, max_length=2)),
                ('organisation_city', models.CharField(blank=True, max_length=250)),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Organisation email')),
                ('year_of_registration', models.IntegerField(blank=True, null=True)),
                ('reach_out', models.TextField(blank=True, help_text='What kind of advice, comments or feedback would you like to receive about your idea from others on the platform? (max. 300 characters)', max_length=300, verbose_name='Reach out – get feedback, ideas and inspiration from the Civic Europe online Community!')),
                ('how_did_you_hear', models.CharField(choices=[('personal_contact', 'Personal contact'), ('websites', 'Website'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('newsletter', 'Newsletter'), ('other', 'Other')], max_length=255, verbose_name='How did you hear about Civic Europe?')),
                ('idea_challenge_camp_represent', models.TextField(help_text='Specify one person only.', max_length=150, verbose_name='Who will represent your idea at the Idea Challenge Camp and why?')),
                ('idea_challenge_camp_benefit', models.TextField(help_text='Tell us about your expectations. Think about your skills, resources, networks and partners when describing what you could offer and what you would like to take away. (max. 300 characters)', max_length=300, verbose_name='How could you contribute to and benefit from participating in the Idea Challenge Camp?')),
                ('idea_title', models.CharField(help_text='Give your idea a short and meaningful title. (max. 50 characters)', max_length=50)),
                ('idea_subtitle', models.CharField(blank=True, help_text='(max. 200 characters)', max_length=200)),
                ('idea_pitch', models.TextField(help_text='Present your idea in max. 500 characters. Share a concise and appealing text that makes the reader curious. Try to pitch your main challenge, objective, method and target group in 3-5 sentences.', max_length=500)),
                ('idea_image', adhocracy4.images.fields.ConfiguredImageField('idea_image', blank=True, help_text='Upload a photo or illustration that visually supports or explains your idea. Make sure that you have the property rights to share this picture. You can upload a .jpg, .png or .gif of up to 3 MB in size. The image should be in landscape (not portrait) format and have a width of at least 400 pixels.', upload_to='ideas/images', verbose_name='Visualise your idea')),
                ('idea_topics', multiselectfield.db.fields.MultiSelectField(choices=[('democracy_participation', 'Democracy and participation'), ('arts_cultural_activities', 'Arts and cultural activities'), ('environment', 'Environment'), ('social_inclusion', 'Social inclusion'), ('migration', 'Migration'), ('communities', 'Communities'), ('urban_development', 'Urban development'), ('education', 'Education')], help_text='Choose 1-2 topics that describe your idea. Your answer to this question does not influence the selection process. It helps us to get a better overview of the proposals we receive.', max_length=255, verbose_name='Topic')),
                ('idea_topics_other', models.CharField(blank=True, help_text='Please specify. (max 250 characters)', max_length=250, verbose_name='Other')),
                ('idea_location', multiselectfield.db.fields.MultiSelectField(choices=[('city', 'City, country or region (please specify below)'), ('online', 'Online'), ('ruhr_linkage', 'Links to the Ruhr area of Germany')], help_text='Where will your idea take place? Choose all options that apply. 1-3 choices possible.', max_length=250, verbose_name='Location')),
                ('idea_location_specify', models.TextField(blank=True, help_text='Please specify the city, country and/or region, e.g. Berlin, Germany. (max. 100 characters)', max_length=100, verbose_name='Location details')),
                ('idea_location_ruhr', models.TextField(blank=True, help_text='Is your project connected to the Ruhr area of Germany through project partners or audiences? Please provide further details. (max. 500 characters)', max_length=500, verbose_name='Links to the Ruhr area')),
                ('challenge', models.TextField(help_text='How does your idea address the challenges of democracy in Europe today? How does it suit our 2017-2018 call for ideas for democracy in Europe? (max. 800 characters)', max_length=800, verbose_name='How will your idea strengthen democracy in Europe?')),
                ('outcome', models.TextField(help_text='If your idea is selected, what will be different a year from now? What will have changed? (max. 800 characters)', max_length=800, verbose_name='What would be a successful outcome for your idea?')),
                ('plan', models.TextField(help_text='Describe as concretely as possible the approach and/or the method you will use when implementing your idea. What are the steps you plan to take? (max. 800 characters)', max_length=800, verbose_name='How do you plan to get there?')),
                ('importance', models.TextField(help_text='What motivates you to bring this idea to life? What is your story? What is your connection and mission behind the idea? (max. 800 characters)', max_length=800, verbose_name='Why is this idea important to you?')),
                ('target_group', models.TextField(help_text='Which target groups, stakeholders, beneficiaries or audiences are at the centre of your idea? (max. 800 characters)', max_length=800, verbose_name='Who are you doing it for and/or with?')),
                ('members', models.TextField(help_text='Please introduce us to the main members of your project team and briefly summarise their experience and skills. (max. 800 characters)', max_length=800, verbose_name='Who is in your project team?')),
                ('partner_organisation_1_name', models.CharField(blank=True, max_length=300, verbose_name='Organisation Name')),
                ('partner_organisation_1_website', models.URLField(blank=True, max_length=500, verbose_name='website')),
                ('partner_organisation_1_country', django_countries.fields.CountryField(blank=True, countries=apps.ideas.countries.EuropeanCountries, max_length=2, verbose_name='country')),
                ('partner_organisation_2_name', models.CharField(blank=True, max_length=300, verbose_name='Organisation Name')),
                ('partner_organisation_2_website', models.URLField(blank=True, max_length=500, verbose_name='website')),
                ('partner_organisation_2_country', django_countries.fields.CountryField(blank=True, countries=apps.ideas.countries.EuropeanCountries, max_length=2, verbose_name='country')),
                ('partner_organisation_3_name', models.CharField(blank=True, max_length=300, verbose_name='Organisation Name')),
                ('partner_organisation_3_website', models.URLField(blank=True, max_length=500, verbose_name='website')),
                ('partner_organisation_3_country', django_countries.fields.CountryField(blank=True, countries=apps.ideas.countries.EuropeanCountries, max_length=2, verbose_name='country')),
                ('partners_more_info', models.TextField(blank=True, help_text='Please use this field if you have more than 3 partner organisations or if you want to tell us more about your proposed partnership arrangements (max. 200 characters).', max_length=200, verbose_name='More information')),
                ('co_workers', models.ManyToManyField(blank=True, related_name='ideasketcharchived_co_workers', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idea_sketch_archived', to='civic_europe_ideas.Idea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdeaFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('followable', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='civic_europe_ideas.Idea')),
            ],
            options={
                'abstract': False,
                'unique_together': {('followable', 'creator')},
            },
        ),
    ]
