# Generated by Django 2.2.9 on 2020-01-20 15:59

import adhocracy4.images.fields
import apps.ideas.countries
import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a4modules', '0005_module_is_draft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='a4modules.Item')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('lead_organisation_name', models.CharField(blank=True, help_text='If you do not yet have a registered organisation, please write the name of your initiative or planned organisation here.', max_length=300, verbose_name='Lead organisation name')),
                ('lead_organisation_status', models.CharField(choices=[('NP', 'I am applying on behalf of a registered non-profit organisation, e.g. NGO'), ('PL', 'Registration as a non-profit organisation is planned or is already underway'), ('HN', 'I have a really good idea, but will need help to register a non-profit organisation'), ('OT', 'Other')], max_length=255, verbose_name='Lead organisation status')),
                ('lead_organisation_details', models.TextField(blank=True, help_text='Please provide details about your current status, especially if you selected "Other" (max. 200 characters)', max_length=200, verbose_name='Lead organisation details')),
                ('lead_organisation_website', models.URLField(blank=True, max_length=500)),
                ('lead_organisation_country', django_countries.fields.CountryField(blank=True, countries=apps.ideas.countries.EuropeanCountries, max_length=2)),
                ('lead_organisation_city', models.CharField(blank=True, max_length=250)),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Lead organisation email')),
                ('year_of_registration', models.IntegerField(blank=True, null=True)),
                ('total_budget', models.IntegerField(help_text='Please indicate your overall budget. The total budget may (but does not have to) include the applicant’s own contribution and/or external sources of funding.', verbose_name='Total budget')),
                ('budget_requested', models.IntegerField(help_text='Funding requested from Civic Europe can range from 1 to 50,000 EUR. Depending on your planning, the amount entered here can be the same as the “total budget” figure entered above.', verbose_name='Funding requested from Civic Europe')),
                ('major_expenses', models.TextField(help_text='What are the major expenses you foresee for the implementation of your idea? Please share a rough estimate by cost category (e.g. office expenses 1000 EUR, travel and accommodation costs 3000 EUR, public relations 2000 EUR, personnel costs etc.)', max_length=500, verbose_name='Major expenses')),
                ('duration', models.IntegerField(help_text='How many months will it take to implement your idea?', verbose_name='Duration of idea (number of months)')),
                ('title', models.CharField(help_text='Give your idea a short and meaningful title (max. 50 characters).', max_length=50)),
                ('subtitle', models.CharField(blank=True, help_text='(max. 200 characters)', max_length=200)),
                ('pitch', models.TextField(help_text='Share a concise and appealing text that makes the reader curious. Summarise your main challenge, objective, target group, approach or activities, and intended impact in 3-5 sentences. (max. 500 characters)', max_length=500)),
                ('image', adhocracy4.images.fields.ConfiguredImageField('image', blank=True, help_text='Upload a photo or illustration that visually supports or explains your idea. Make sure that you have the property rights to share this picture. You can upload a .jpg, .png or .gif up to 3 MB in size. The image should be in landscape (not portrait) format and have a width of at least 400 pixels.', upload_to='ideas/images', verbose_name='Visualise your idea')),
                ('topics', multiselectfield.db.fields.MultiSelectField(choices=[('DP', 'Democracy and participation'), ('CE', 'Civic education'), ('CD', 'Community development'), ('UP', 'Urban and rural development'), ('SI', 'Social inclusion'), ('MI', 'Migration'), ('ES', 'Environment & sustainability'), ('AC', 'Arts and cultural activities')], help_text='Choose 1-2 topics that fit to your idea. Your answer to this question does not influence the selection process. It helps to get a better overview of the ideas.', max_length=255, verbose_name='Topic')),
                ('topics_other', models.CharField(blank=True, help_text='Please specify. (max 250 characters)', max_length=250, verbose_name='Other')),
                ('location', models.TextField(help_text='We are looking for initiatives that will take place outside of the big urban centres that are attuned to polarisation or have a low density of cohesion in society and with few possibilities for engagement. Which region is mainly affected by your project? Please name city, country and/or region e.g. Teleorman, south Romania. (max. 100 characters)', max_length=100, verbose_name='Where will your project idea take place? ')),
                ('challenge', models.TextField(help_text='Tell us more about the region your project idea is based in and what challenges it faces regarding democracy and societal cohesion. What problem(s) are you trying to solve? (max. 800 characters)', max_length=800, verbose_name='What is the specific societal challenge faced by the region in which your project idea is based?')),
                ('impact', models.TextField(help_text='We are looking for ideas that strengthen democracy and citizenship as a living practice in local communities. How does your idea enhance citizens’ engagement and participation? (max. 800 characters)', max_length=800, verbose_name='How does your idea strengthen democracy and citizenship as a living practice at a local and community level? Please refer to your described challenge.')),
                ('target_group', models.TextField(help_text='We are looking for ideas that try to engage different perspectives from all local voices of the communities including those who feel excluded. Please describe what target groups, beneficiaries or audiences will be affected by your idea. How will you include the whole range of opinions on the issue? Try to add some key figures about the groups of people you are going to be working with. (max. 800 characters)', max_length=800, verbose_name='Who are you doing it for? ')),
                ('local_embedding', models.TextField(help_text='How will you be working with local supporters, partners and/or allies? Please refer to established networks you might have or want to establish and/or possible institutional supporters (administrational bodies, organisations). (max. 800 characters)', max_length=800, verbose_name='How is your idea embedded locally? ')),
                ('uniqueness', models.TextField(help_text='Please describe what niche your initiative is filling in the specific region and context you are describing above. (max. 800 characters)', max_length=800, verbose_name='What makes your idea stand apart in its local and regional dimension? ')),
                ('network', models.TextField(help_text='Winning projects meet at least one time per year in network meetings and receive mentoring and support from the Civic Europe team. Tell us about your expectations. Think about your skills, resources, networks and partners when describing what you could offer and what you would like to take away. (max. 800 characters)', max_length=800, verbose_name='How will you contribute to and benefit from the Civic Europe network? ')),
                ('feedback', models.TextField(blank=True, help_text='What kind of advice, comments or feedback would you like to receive about your idea from others on the platform? (max. 300 characters)', max_length=300, verbose_name='Reach out – get feedback, ideas and inspiration from the Civic Europe online community!')),
                ('partner_organisation_1_name', models.CharField(blank=True, max_length=300, verbose_name='Organisation Name')),
                ('partner_organisation_1_website', models.URLField(blank=True, max_length=500, verbose_name='website')),
                ('partner_organisation_1_country', django_countries.fields.CountryField(blank=True, countries=apps.ideas.countries.EuropeanCountries, max_length=2, verbose_name='country')),
                ('partner_organisation_2_name', models.CharField(blank=True, max_length=300, verbose_name='Organisation Name')),
                ('partner_organisation_2_website', models.URLField(blank=True, max_length=500, verbose_name='website')),
                ('partner_organisation_2_country', django_countries.fields.CountryField(blank=True, countries=apps.ideas.countries.EuropeanCountries, max_length=2, verbose_name='country')),
                ('partner_organisation_3_name', models.CharField(blank=True, max_length=300, verbose_name='Organisation Name')),
                ('partner_organisation_3_website', models.URLField(blank=True, max_length=500, verbose_name='website')),
                ('partner_organisation_3_country', django_countries.fields.CountryField(blank=True, countries=apps.ideas.countries.EuropeanCountries, max_length=2, verbose_name='country')),
                ('partners_more_info', models.TextField(blank=True, help_text='Please use this field if you have more than 3 partner organisations or if you want to tell us more about your proposed partnership arrangements (max. 200 characters).', max_length=200, verbose_name='More information')),
                ('plan', models.TextField(help_text='Please describe the specific steps, interventions, methods and/or approach you will undertake to implement your project idea. (max. 800 characters)', max_length=800, verbose_name='How do you plan to get there?')),
                ('reach_out', models.TextField(help_text='Through what actions, measures or channels will you be reaching out to your key target groups and others to whom your project idea is relevant? (max. 800 characters)', max_length=800, verbose_name='How will you be reaching out to others and advocating your project idea?')),
                ('results', models.TextField(help_text='If your idea is selected, what will be different a year from now? What would success look like for you? Think back to the challenge your project is addressing - what will have changed, in part, thanks to your project? How is the local community empowered? (max. 800 characters)', max_length=800, verbose_name='What are the expected results?')),
                ('sustainability', models.TextField(help_text='What actions or next steps will you take in order to ensure that your initiative continues beyond the project funding?', max_length=800, verbose_name='How will you ensure the sustainability of your initiative?')),
                ('contribution', models.TextField(help_text='Please share how your idea relates to the bigger picture and strengthens democracy in Europe. (max. 800 characters)', max_length=800, verbose_name='How does your initiative contribute to strengthening democracy in Europe? ')),
                ('knowledge', models.TextField(help_text='We are looking for people that know the community and region they are working with, although everybody with a solid background can apply. Please introduce your project team and briefly summarise their experience and skills. Tell us how you are connected to the region your idea will take place in and how do you know about the specificities of its civic landscape. (max. 800 characters).', max_length=800, verbose_name='Why are you the right people for responding to this challenge?')),
                ('motivation', models.TextField(help_text='What motivates you to bring this idea to life? What is your connection and mission behind the idea? (max. 800 characters)', max_length=800, verbose_name='Why is this idea important to you?')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('is_on_shortlist', models.BooleanField(default=False)),
                ('is_winner', models.BooleanField(default=False)),
                ('jury_statement', models.TextField(blank=True, verbose_name='Why this idea?')),
                ('community_award_winner', models.BooleanField(default=False)),
                ('budget_granted', models.IntegerField(blank=True, null=True)),
                ('co_workers', models.ManyToManyField(blank=True, help_text='Here you can insert the email addresses of up to 5 team members. They will receive an email inviting them to register on the Civic Europe website. After registering they will appear with their user name on your idea page and will be able to edit your idea.', related_name='idea_co_workers', to=settings.AUTH_USER_MODEL, verbose_name='Please add your team members here.')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
            bases=('a4modules.item', models.Model),
        ),
        migrations.CreateModel(
            name='IdeaFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('followable', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='civic_europe_ideas.Idea')),
            ],
            options={
                'abstract': False,
                'unique_together': {('followable', 'creator')},
            },
        ),
    ]
