# Generated by Django 2.2.10 on 2020-03-09 12:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('civic_europe_ideas', '0002_local_wording_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='topics',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('DP', 'Democracy and participation'), ('CE', 'Civic education'), ('CD', 'Community development'), ('UP', 'Urban and rural development'), ('SI', 'Social inclusion'), ('MI', 'Migration'), ('ES', 'Environment and sustainability'), ('AC', 'Arts and cultural activities')], help_text='Choose 1-2 topics that fit to your idea. Your answer to this question does not influence the selection process. It helps to get a better overview of the ideas.', max_length=255, verbose_name='Topic'),
        ),
    ]
