# Generated by Django 2.2.11 on 2020-03-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_europe_ideas', '0003_change_of_topic_choices_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='first_name',
            field=models.CharField(help_text='Your first and last name will be published together with the application.', max_length=250),
        ),
    ]
