# Generated by Django 2.2.14 on 2020-12-17 10:21

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('civic_europe_ideas', '0004_adds_helptext_to_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='lead_organisation_city',
            new_name='lead_organisation_location_name',
        ),
        migrations.AddField(
            model_name='idea',
            name='clarification_legal_status',
            field=models.TextField(blank=True, help_text='If you selected “Other,” please provide details about your current organisation status (max. 200 characters)', max_length=200, verbose_name='Clarification legal status'),
        ),
        migrations.AddField(
            model_name='idea',
            name='lead_organisation_location',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CC', 'Capital city'), ('LA', 'Large urban area (population of more than 500,000 inhabitants)'), ('UA', 'City/urban area (population of at least 50,000 inhabitants and a density of >1,500 inhabitants per km2, most inhabitants have nonagricultural jobs, there is good infrastructure such as housing, commercial buildings, roads, bridges, and railways)'), ('TW', 'Town (population of at least 5,000 inhabitants and a density of at least 300 inhabitants per km2)'), ('RA', 'Village/rural area (population less than 5,000 inhabitants, low population density, largely lacking or poor infrastructure)')], help_text='Please specify the type of the location to help us better understand the ideas. If your organisation is based in more than one location, you can choose more options. The numbers here are more for orientation, you don’t have to look up the exact numbers; a rough estimate will suffice.', max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='first_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='idea',
            name='lead_organisation_details',
            field=models.TextField(blank=True, help_text='Please describe main goals, vision and activities of your organisation (max. 500 characters)', max_length=500, verbose_name='Lead organisation details'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='lead_organisation_status',
            field=models.CharField(choices=[('NP', 'I am applying on behalf of a registered non-profit organisation'), ('CH', 'I am applying on behalf of a registered organisation with charitable purpose'), ('PI', 'I am applying on behalf of a public institution'), ('PL', 'Registration as a non-profit organisation or organisation with charitable purpose is planned or is already underway'), ('OT', 'Other')], max_length=255, verbose_name='Lead organisation status'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='lead_organisation_website',
            field=models.URLField(blank=True, help_text='Please enter the website of your organisation here. If you don’t have one, please enter your Facebook page or similar online presence.', max_length=500, verbose_name='Lead organisation online presence (website or social media presence)'),
        ),
    ]
