# Generated by Django 2.2.14 on 2020-12-22 17:41

import adhocracy4.images.fields
import apps.ideas.countries
from django.db import migrations, models
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('civic_europe_ideas', '0007_change_partners_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='country_of_implementation',
            field=django_countries.fields.CountryField(blank=True, countries=apps.ideas.countries.EuropeanCountries, help_text='You can choose multiple options if your project takes place in more than one country.', max_length=35, multiple=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='field_of_action',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CD', 'Community development'), ('SI', 'Social inclusion'), ('ES', 'Environment and sustainability'), ('AC', 'Arts and cultural activities'), ('HR', 'Human rights'), ('YP', 'Youth participation and empowerment'), ('JL', 'Journalism'), ('SE', '(Social) Entrepreneurship'), ('OT', 'Other')], help_text='Project ideas should be based on democratic values like human dignity, tolerance, freedom and diversity of opinion and the rule of law. They should also strengthen civic engagement and participation, ideally by means of civic education. Please choose 1-2 of the fields below that suit your idea. This will not influence the selection process, but will help users to filter the ideas in the idea space.', max_length=255),
        ),
        migrations.AddField(
            model_name='idea',
            name='field_of_action_other',
            field=models.CharField(blank=True, help_text='(max. 50 characters)', max_length=50, verbose_name='If you chose “Other” please specify briefly here'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=adhocracy4.images.fields.ConfiguredImageField('image', help_text='Upload a photo or illustration that visually supports or explains your idea. The picture will not influence the selection process but it will be used as a header picture of your idea on the website. Make sure that you have the property rights to share this picture. You can upload a .jpg, .png or .gif up to 3 MB in size. The image should be in landscape (not portrait) format and have a width of at least 400 pixels.', upload_to='ideas/images', verbose_name='Visualise your idea'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='pitch',
            field=models.TextField(help_text='Share a concise and appealing text that summarizes your idea, makes the reader want to learn more and that is memorable. Summarize the challenge you are tackling, your objective, target group and approach in 3-5 sentences. (max. 500 characters)', max_length=500, verbose_name='Idea pitch'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Here you can add a short explanation of your title (max. 200 characters). For instance: “Fostering a culture of democratic dialogue and co-designing a vision for the development of a small island.”', max_length=200, verbose_name='Idea subtitle'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(help_text='Give your idea a short and meaningful title (max. 50 characters). For instance: “Islands of Hope”', max_length=50, verbose_name='Idea title'),
        ),
    ]
