# Generated by Django 2.2.14 on 2020-12-22 17:49

import apps.ideas.countries
from django.db import migrations
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('civic_europe_ideas', '0009_map_topic_to_field_of_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='topics_other',
        ),
        migrations.AlterField(
            model_name='idea',
            name='country_of_implementation',
            field=django_countries.fields.CountryField(countries=apps.ideas.countries.EuropeanCountries, help_text='You can choose multiple options if your project takes place in more than one country.', max_length=35, multiple=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='field_of_action',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CD', 'Community development'), ('SI', 'Social inclusion'), ('ES', 'Environment and sustainability'), ('AC', 'Arts and cultural activities'), ('HR', 'Human rights'), ('YP', 'Youth participation and empowerment'), ('JL', 'Journalism'), ('SE', '(Social) Entrepreneurship'), ('OT', 'Other')], help_text='Project ideas should be based on democratic values like human dignity, tolerance, freedom and diversity of opinion and the rule of law. They should also strengthen civic engagement and participation, ideally by means of civic education. Please choose 1-2 of the fields below that suit your idea. This will not influence the selection process, but will help users to filter the ideas in the idea space.', max_length=255),
        ),
    ]
