# Generated by Django 2.2.17 on 2020-12-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_europe_ideas', '0010_remove_topics_make_field_of_action_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='location',
            field=models.CharField(help_text='Please name city, country and/or region (max. 100 characters). For instance: “Teleorman, south Romania.” ', max_length=100, verbose_name='Where will your project take place?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='challenge',
            field=models.TextField(help_text='Tell us more about the region your project idea is based in and what challenges it faces regarding democracy and societal cohesion. What problem(s) are you trying to solve? (max. 800 characters)', max_length=800, verbose_name='What is the specific societal challenge faced by the region in which your project idea is based? '),
        ),
        migrations.AlterField(
            model_name='idea',
            name='impact',
            field=models.TextField(help_text='We are looking for ideas that strengthen democracy and active citizenship in local communities. How does your idea enhance citizens’ engagement and participation? (max. 800 characters)', max_length=800, verbose_name='How does your idea strengthen democracy and active citizenship at a local and community level? Please refer to your described challenge. '),
        ),
        migrations.AlterField(
            model_name='idea',
            name='local_embedding',
            field=models.TextField(help_text='Networks, allies, public bodies or others you want to include in order to implement your project successfully. (max. 800 characters)', max_length=800, verbose_name='Who else, besides the key target group(s), will you work with or involve in your project? '),
        ),
        migrations.AlterField(
            model_name='idea',
            name='location',
            field=models.CharField(help_text='Please name city, country and/or region (max. 100 characters). For instance: “Teleorman, south Romania.” ', max_length=100, verbose_name='Where will your project take place? '),
        ),
        migrations.AddField(
            model_name='idea',
            name='location_details',
            field=models.CharField(choices=[('CC', 'Capital city'), ('LA', 'Large urban area (population of more than 500,000 inhabitants)'), ('UA', 'City/urban area (population of at least 50,000 inhabitants and a density of >1,500 inhabitants per km2, most inhabitants have nonagricultural jobs, there is good infrastructure such as housing, commercial buildings, roads, bridges, and railways)'), ('TW', 'Town (population of at least 5,000 inhabitants and a density of at least 300 inhabitants per km2)'), ('RA', 'Village/rural area (population less than 5,000 inhabitants, low population density, largely lacking or poor infrastructure)'), ('ML', 'Mixed location (if your project will take place in several locations)')], default='ML', help_text='Please specify the type of the location. We are aware that national definitions of urban and rural areas differ significantly and places with the same number of inhabitants can be perceived in some countries as urban and in others as rural. This question merely helps us to better categorize the prospective locations.', max_length=2, verbose_name='Location '),
        ),
        migrations.AlterField(
            model_name='idea',
            name='target_group',
            field=models.TextField(help_text='Please describe the key target groups that you want to reach with your project. Try to add some key figures about the groups you will be working with. (max. 800 characters)', max_length=800, verbose_name='Who are you doing it for? '),
        ),
        migrations.AlterField(
            model_name='idea',
            name='challenge',
            field=models.TextField(help_text='Please be concise and refer only to the challenge(s) that your project will address. If possible, link this answer to your previous answer. (max. 800 characters) ', max_length=800, verbose_name='What is the specific societal challenge faced by this region that you aim to tackle with your project? '),
        ),
        migrations.AlterField(
            model_name='idea',
            name='impact',
            field=models.TextField(blank=True, help_text='We are looking for ideas that strengthen democracy and active citizenship in local communities. How does your idea enhance citizens’ engagement and participation? (max. 800 characters)', max_length=800, verbose_name='How does your idea strengthen democracy and active citizenship at a local and community level? Please refer to your described challenge. '),
        ),
        migrations.AlterField(
            model_name='idea',
            name='uniqueness',
            field=models.TextField(blank=True, help_text='Please describe what niche your initiative is filling in the specific region and context you are describing above. (max. 800 characters)', max_length=800, verbose_name='What makes your idea stand apart in its local and regional dimension? '),
        ),
        migrations.AddField(
            model_name='idea',
            name='location_details_mixed',
            field=models.CharField(blank=True, help_text='(max. 100 characters)', max_length=100, verbose_name='If you chose “Mixed location”, please specify them briefly here. '),
        ),
        migrations.AddField(
            model_name='idea',
            name='cohesion',
            field=models.TextField(default='This question did not exist when this idea was created', help_text='Civic cohesion is defined as the ability, knowledge and willingness of individuals to cooperate with each other in order to prosper, grow and learn as a community in a changing world. Is this not the case in this region and why? Do community members lack an understanding that citizens can act and contribute to positive change in their community and why? Does the civic infrastructure include a striving civil society sector, informal groups, access to decision and policymaking, community centers, libraries, museums, etc.? Please specify. (max. 800 characters)', max_length=800, verbose_name='Why is this region or community lacking civic cohesion and engagement? '),
        ),
        migrations.AddField(
            model_name='idea',
            name='perspective_and_dialog',
            field=models.TextField(default='This question did not exist when this idea was created', help_text='We are looking for ideas that try to build bridges between differently-minded people. How will you invite people who have different opinions or different perspectives to engage? How will you ensure that marginalized voices or perspectives can be heard? (max. 800 characters)', max_length=800, verbose_name='How will you engage different perspectives in dialogue around the societal challenge that you aim to tackle? '),
        ),
    ]
