# Generated by Django 2.2.17 on 2020-12-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_europe_ideas', '0011_change_local_dimension_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='contribution',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='knowledge',
        ),
        migrations.AlterField(
            model_name='idea',
            name='impact',
            field=models.TextField(blank=True, help_text='How will your project help community members get actively involved in a social or political issue in their (local) community to improve their quality of life? How will your project give them a voice in the decision-making and implementation process? If you are using the means of civic education: providing knowledge about institutions, power structures, policies and processes etc. or skills like debating etc., please describe them. (max. 800 characters)', max_length=800, verbose_name='How does your idea strengthen democracy and active citizenship at a local and community level? Please refer to your described challenge. '),
        ),
        migrations.AlterField(
            model_name='idea',
            name='motivation',
            field=models.TextField(help_text='We are looking for people who know the community and region they work with, although anyone with a solid background can apply. Please introduce your project team and briefly summarize their experience and skills. Tell us how you are connected to the region your idea targets and how you know the specifics of its civic landscape.  What motivates you to bring this idea to life? What is your connection and mission? (max. 800 characters)', max_length=800, verbose_name='Who is the team behind the idea and why is this cause important to you?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='plan',
            field=models.TextField(help_text='Please describe the activities, specific steps, methods and approach you will undertake to implement your project. (max. 1400 characters)', max_length=1400, verbose_name='What is your action plan and how do you plan to get there?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='reach_out',
            field=models.TextField(help_text='What actions, measures or (communication) channels will you use to reach out to your key target groups and others to whom your project is relevant? (max. 400 characters)', max_length=400, verbose_name='How will you reach out to others?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='results',
            field=models.TextField(help_text='At the end of your project phase, what will have changed for the better thanks to it? (max. 800 characters)', max_length=800, verbose_name='What are the expected results?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='sustainability',
            field=models.TextField(help_text='What seeds will you plant in order to ensure that your initiative continues beyond the project funding and that you make an impact? Try to be as specific and as realistic as possible. (max. 800 characters)', max_length=800, verbose_name='How do you envision the sustainability of your initiative?'),
        ),
    ]
