# Generated by Django 2.2.17 on 2020-12-29 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_europe_ideas', '0012_change_road_to_impact_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='budget_requested',
            field=models.IntegerField(help_text='Funding requested from Civic Europe can range from 1 to 50,000 EUR. Depending on your planning, the amount entered here can be the same as the “total budget” figure entered above.', validators=[django.core.validators.MaxValueValidator(50000), django.core.validators.MinValueValidator(0)], verbose_name='Funding requested from Civic Europe'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='total_budget',
            field=models.IntegerField(help_text='Please indicate your overall budget. The total budget may (but does not have to) include the applicant’s own contribution and/or external sources of funding.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total budget'),
        ),
    ]
