# Generated by Django 2.2.17 on 2020-12-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_europe_ideas', '0013_change_finances_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='feedback',
            field=models.TextField(blank=True, help_text='Shortened versions of all ideas will be published in our idea space, an open space where registered users can comment on the ideas. What kind of advice, comments or feedback would you like to receive about your idea from others on the platform? (max. 300 characters)', max_length=300, verbose_name='Reach out – get feedback, ideas and inspiration from the Civic Europe online community!'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='network',
            field=models.TextField(help_text='Winning projects meet at least once per year in network meetings and participate in peer-to-peer learning activities as well as trainings. Think about your skills, resources, networks and partners when describing what you could offer and what you would like to take away from such network meetings. (max. 800 characters)', max_length=800, verbose_name='How will you contribute to and benefit from the Civic Europe network? '),
        ),
    ]
