# Generated by Django 2.2.17 on 2021-01-05 10:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('civic_europe_ideas', '0014_update_helptext_network_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='field_of_action',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AC', 'Arts and cultural activities'), ('CD', 'Community development'), ('ER', 'Education and research'), ('ES', 'Environment and sustainability'), ('HL', 'Health'), ('HR', 'Human rights'), ('JL', 'Journalism'), ('LP', 'Law, advocacy and policy'), ('SE', '(Social) Entrepreneurship'), ('SI', 'Social inclusion'), ('YP', 'Youth participation and empowerment'), ('OT', 'Other')], help_text='Project ideas should be based on democratic values like human dignity, tolerance, freedom and diversity of opinion and the rule of law. They should also strengthen civic engagement and participation, ideally by means of civic education. Please choose 1-2 of the fields below that suit your idea. This will not influence the selection process, but will help users to filter the ideas in the idea space.', max_length=255),
        ),
    ]
