# Generated by Django 2.2.17 on 2021-01-05 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_europe_ideas', '0015_update_field_of_action_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='year_of_registration',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(0)]),
        ),
    ]
