# Generated by Django 2.2.17 on 2021-01-06 16:15

import adhocracy4.images.fields
import apps.ideas.countries
import django.core.validators
from django.db import migrations, models
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('civic_europe_ideas', '0016_add_validator_to_year_of_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='budget_requested',
            field=models.IntegerField(help_text='Funding requested from Civic Europe can range from 1 to 50,000 EUR. Depending on your planning, the amount entered here can be the same as the “total budget” figure entered above. This section will be published in the idea space.', validators=[django.core.validators.MaxValueValidator(50000), django.core.validators.MinValueValidator(0)], verbose_name='Funding requested from Civic Europe'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='challenge',
            field=models.TextField(help_text='Please be concise and refer only to the challenge(s) that your project will address. If possible, link this answer to your previous answer. This section will be published in the idea space. (Max. 800 characters.)', max_length=800, verbose_name='What is the specific societal challenge faced by this region that you aim to tackle with your project?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='clarification_legal_status',
            field=models.TextField(blank=True, help_text='If you selected “Other,” please provide details about your current organization status. (Max. 200 characters.)', max_length=200, verbose_name='Clarification legal status'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='cohesion',
            field=models.TextField(help_text='Civic cohesion is defined as the ability, knowledge and willingness of individuals to cooperate with each other in order to prosper, grow and learn as a community in a changing world. Is this not the case in this region and why? Do community members lack an understanding that citizens can act and contribute to positive change in their community and why? Does the civic infrastructure include a striving civil society sector, informal groups, access to decision and policymaking, community centers, libraries, museums, etc.? Please specify. (Max. 800 characters.)', max_length=800, verbose_name='Why is this region or community lacking civic cohesion and engagement?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Lead organization email'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='contribution',
            field=models.TextField(blank=True, help_text='Please share how your idea relates to the bigger picture and strengthens democracy in Europe. (Max. 800 characters.)', max_length=800, verbose_name='How does your initiative contribute to strengthening democracy in Europe? '),
        ),
        migrations.AlterField(
            model_name='idea',
            name='feedback',
            field=models.TextField(blank=True, help_text='Shortened versions of all ideas will be published in our idea space, an open space where registered users can comment on the ideas. What kind of advice, comments or feedback would you like to receive about your idea from others on the platform? This section will be published in the idea space. (Max. 300 characters.)', max_length=300, verbose_name='Reach out – get feedback, ideas and inspiration from the Civic Europe online community!'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='field_of_action',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AC', 'Arts and cultural activities'), ('CD', 'Community development'), ('ER', 'Education and research'), ('ES', 'Environment and sustainability'), ('HL', 'Health'), ('HR', 'Human rights'), ('JL', 'Journalism'), ('LP', 'Law, advocacy and policy'), ('SE', '(Social) Entrepreneurship'), ('SI', 'Social inclusion'), ('YP', 'Youth participation and empowerment'), ('OT', 'Other')], help_text='Project ideas should be based on democratic values like human dignity, tolerance, freedom and diversity of opinion and the rule of law. They should also strengthen civic engagement and participation, ideally by means of civic education. Please choose 1-2 of the fields below that suit your idea. This will not influence the selection process, but will help users to filter the ideas in the idea space. This section will be published in the idea space.', max_length=255),
        ),
        migrations.AlterField(
            model_name='idea',
            name='field_of_action_other',
            field=models.CharField(blank=True, help_text='(Max. 50 characters.)', max_length=50, verbose_name='If you chose “Other” please specify briefly here'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=adhocracy4.images.fields.ConfiguredImageField('image', help_text='Upload a photo or illustration that visually supports or explains your idea. The picture will not influence the selection process but it will be used as a header picture of your idea on the website. Make sure that you have the property rights to share this picture. You can upload a .jpg, .png or .gif up to 3 MB in size. The image should be in landscape (not portrait) format and have a width of at least 400 pixels.', upload_to='ideas/images', verbose_name='Visualize your idea'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='impact',
            field=models.TextField(help_text='How will your project help community members get actively involved in a social or political issue in their (local) community to improve their quality of life? How will your project give them a voice in the decision-making and implementation process? If you are using the means of civic education: providing knowledge about institutions, power structures, policies and processes etc. or skills like debating etc., please describe them. This section will be published in the idea space. (Max. 800 characters.)', max_length=800, verbose_name='How does your idea strengthen active citizenship – social and political engagement and participation – at a local and community level?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='knowledge',
            field=models.TextField(blank=True, help_text='We are looking for people that know the community and region they are working with, although everybody with a solid background can apply. Please introduce your project team and briefly summarise their experience and skills. Tell us how you are connected to the region your idea will take place in and how do you know about the specificities of its civic landscape. (Max. 800 characters).', max_length=800, verbose_name='Why are you the right people for responding to this challenge?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='lead_organisation_country',
            field=django_countries.fields.CountryField(blank=True, countries=apps.ideas.countries.EuropeanCountries, max_length=2, verbose_name='Lead organization country'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='lead_organisation_details',
            field=models.TextField(blank=True, help_text='Please describe main goals, vision and activities of your organization. (Max. 500 characters.)', max_length=500, verbose_name='Lead organization details'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='lead_organisation_location',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CC', 'Capital city'), ('LA', 'Large urban area (population of more than 500,000 inhabitants)'), ('UA', 'City/urban area (population of at least 50,000 inhabitants and a density of >1,500 inhabitants per km², most inhabitants have nonagricultural jobs, there is good infrastructure such as housing, commercial buildings, roads, bridges, and railways)'), ('TW', 'Town (population of at least 5,000 inhabitants and a density of at least 300 inhabitants per km²)'), ('RA', 'Village/rural area (population less than 5,000 inhabitants, low population density, largely lacking or poor infrastructure)')], help_text='Please specify the type of the location to help us better understand the ideas. If your organization is based in more than one location, you can choose more options. The numbers here are more for orientation, you don’t have to look up the exact numbers; a rough estimate will suffice.', max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='lead_organisation_location_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Lead organization location name'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='lead_organisation_name',
            field=models.CharField(blank=True, help_text='If you do not yet have a registered organization, please write the name of your initiative or planned organization here. This section will be published in the idea space.', max_length=300, verbose_name='Lead organization name'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='lead_organisation_status',
            field=models.CharField(choices=[('NP', 'I am applying on behalf of a registered non-profit organization'), ('CH', 'I am applying on behalf of a registered organization with charitable purpose'), ('PI', 'I am applying on behalf of a public institution'), ('PL', 'Registration as a non-profit organization or organization with charitable purpose is planned or is already underway'), ('OT', 'Other')], max_length=255, verbose_name='Lead organization status'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='lead_organisation_website',
            field=models.URLField(blank=True, help_text='Please enter the website of your organization here. If you don’t have one, please enter your Facebook page or similar online presence. This section will be published in the idea space.', max_length=500, verbose_name='Lead organization online presence (website or social media presence)'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='local_embedding',
            field=models.TextField(help_text='Networks, allies, public bodies or others you want to include in order to implement your project successfully. (Max. 800 characters.)', max_length=800, verbose_name='Who else, besides the key target group(s), will you work with or involve in your project?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='location',
            field=models.CharField(help_text='Please name city, country and/or region, for instance: “Teleorman, south Romania.”. This section will be published in the idea space. (Max. 100 characters.)', max_length=100, verbose_name='Where will your project take place?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='location_details',
            field=models.CharField(choices=[('CC', 'Capital city'), ('LA', 'Large urban area (population of more than 500,000 inhabitants)'), ('UA', 'City/urban area (population of at least 50,000 inhabitants and a density of >1,500 inhabitants per km², most inhabitants have nonagricultural jobs, there is good infrastructure such as housing, commercial buildings, roads, bridges, and railways)'), ('TW', 'Town (population of at least 5,000 inhabitants and a density of at least 300 inhabitants per km²)'), ('RA', 'Village/rural area (population less than 5,000 inhabitants, low population density, largely lacking or poor infrastructure)'), ('ML', 'Mixed location (if your project will take place in several locations)')], default='ML', help_text='Please specify the type of the location. We are aware that national definitions of urban and rural areas differ significantly and places with the same number of inhabitants can be perceived in some countries as urban and in others as rural. This question merely helps us to better categorize the prospective locations.', max_length=2, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='location_details_mixed',
            field=models.CharField(blank=True, help_text='(Max. 100 characters.)', max_length=100, verbose_name='If you chose “Mixed location”, please specify them briefly here.'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='major_expenses',
            field=models.TextField(help_text='What are the major expenses you foresee for the implementation of your idea? Please share a rough estimate by cost category (e.g. office expenses 1000 EUR, travel and accommodation costs 3000 EUR, public relations 2000 EUR, personnel costs etc.) This section will be published in the idea space.', max_length=500, verbose_name='Major expenses'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='motivation',
            field=models.TextField(help_text='We are looking for people who know the community and region they work with, although anyone with a solid background can apply. Please introduce your project team and briefly summarize their experience and skills. Tell us how you are connected to the region your idea targets and how you know the specifics of its civic landscape.  What motivates you to bring this idea to life? What is your connection and mission? This section will be published in the idea space. (Max. 800 characters.)', max_length=800, verbose_name='Who is the team behind the idea and why is this cause important to you?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='network',
            field=models.TextField(help_text='Winning projects meet at least once per year in network meetings and participate in peer-to-peer learning activities as well as trainings. Think about your skills, resources, networks and partners when describing what you could offer and what you would like to take away from such network meetings. (Max. 800 characters.)', max_length=800, verbose_name='How will you contribute to and benefit from the Civic Europe network?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_1_details',
            field=models.CharField(blank=True, help_text='Please describe main goals, vision and activities of the organization. Please also mention the organization status (NGO, public institution, enterprise, etc.). Any organization status is possible for partners. (Max. 400 characters.)', max_length=400, verbose_name='Partner organization details'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_1_location',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CC', 'Capital city'), ('LA', 'Large urban area (population of more than 500,000 inhabitants)'), ('UA', 'City/urban area (population of at least 50,000 inhabitants and a density of >1,500 inhabitants per km², most inhabitants have nonagricultural jobs, there is good infrastructure such as housing, commercial buildings, roads, bridges, and railways)'), ('TW', 'Town (population of at least 5,000 inhabitants and a density of at least 300 inhabitants per km²)'), ('RA', 'Village/rural area (population less than 5,000 inhabitants, low population density, largely lacking or poor infrastructure)')], help_text='Please specify the type of the location to help us better understand the ideas. If your partner organization is based in more than one location, you can choose more options. The numbers here are more for orientation, you don’t have to look up the exact numbers; a rough estimate will suffice.', max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_1_name',
            field=models.CharField(blank=True, help_text='This section will be published in the idea space.', max_length=300, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_1_role',
            field=models.CharField(blank=True, help_text='Why did you choose this partner and how will your partner support you? (Max. 400 characters.)', max_length=400, verbose_name='Please describe the role of your partner in your project'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_1_website',
            field=models.URLField(blank=True, help_text='Please enter the website of your partner here. If they don’t have one, please enter their Facebook page or similar online presence. This section will be published in the idea space.', max_length=500, verbose_name='Online presence (website or social media presence)'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_2_details',
            field=models.CharField(blank=True, help_text='Please describe main goals, vision and activities of the organization. Please also mention the organization status (NGO, public institution, enterprise, etc.). Any organization status is possible for partners. (Max. 400 characters.)', max_length=400, verbose_name='Partner organization details'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_2_location',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CC', 'Capital city'), ('LA', 'Large urban area (population of more than 500,000 inhabitants)'), ('UA', 'City/urban area (population of at least 50,000 inhabitants and a density of >1,500 inhabitants per km², most inhabitants have nonagricultural jobs, there is good infrastructure such as housing, commercial buildings, roads, bridges, and railways)'), ('TW', 'Town (population of at least 5,000 inhabitants and a density of at least 300 inhabitants per km²)'), ('RA', 'Village/rural area (population less than 5,000 inhabitants, low population density, largely lacking or poor infrastructure)')], help_text='Please specify the type of the location to help us better understand the ideas. If your partner organization is based in more than one location, you can choose more options. The numbers here are more for orientation, you don’t have to look up the exact numbers; a rough estimate will suffice.', max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_2_name',
            field=models.CharField(blank=True, help_text='This section will be published in the idea space.', max_length=300, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_2_role',
            field=models.CharField(blank=True, help_text='Why did you choose this partner and how will your partner support you? (Max. 400 characters.)', max_length=400, verbose_name='Please describe the role of your partner in your project'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_2_website',
            field=models.URLField(blank=True, help_text='Please enter the website of your partner here. If they don’t have one, please enter their Facebook page or similar online presence. This section will be published in the idea space.', max_length=500, verbose_name='Online presence (website or social media presence)'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_3_details',
            field=models.CharField(blank=True, help_text='Please describe main goals, vision and activities of the organization. Please also mention the organization status (NGO, public institution, enterprise, etc.). Any organization status is possible for partners. (Max. 400 characters.)', max_length=400, verbose_name='Partner organization details'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_3_location',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CC', 'Capital city'), ('LA', 'Large urban area (population of more than 500,000 inhabitants)'), ('UA', 'City/urban area (population of at least 50,000 inhabitants and a density of >1,500 inhabitants per km², most inhabitants have nonagricultural jobs, there is good infrastructure such as housing, commercial buildings, roads, bridges, and railways)'), ('TW', 'Town (population of at least 5,000 inhabitants and a density of at least 300 inhabitants per km²)'), ('RA', 'Village/rural area (population less than 5,000 inhabitants, low population density, largely lacking or poor infrastructure)')], help_text='Please specify the type of the location to help us better understand the ideas. If your partner organization is based in more than one location, you can choose more options. The numbers here are more for orientation, you don’t have to look up the exact numbers; a rough estimate will suffice.', max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_3_name',
            field=models.CharField(blank=True, help_text='This section will be published in the idea space.', max_length=300, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_3_role',
            field=models.CharField(blank=True, help_text='Why did you choose this partner and how will your partner support you? (Max. 400 characters.)', max_length=400, verbose_name='Please describe the role of your partner in your project'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_3_website',
            field=models.URLField(blank=True, help_text='Please enter the website of your partner here. If they don’t have one, please enter their Facebook page or similar online presence. This section will be published in the idea space.', max_length=500, verbose_name='Online presence (website or social media presence)'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partners_more_info',
            field=models.TextField(blank=True, help_text='Please use this field if you have more than three partner organizations. Please also let us know about planned partnerships. This section will be published in the idea space. (Max. 200 characters.)', max_length=200, verbose_name='More information'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='perspective_and_dialog',
            field=models.TextField(help_text='We are looking for ideas that try to build bridges between differently-minded people. How will you invite people who have different opinions or different perspectives to engage? How will you ensure that marginalized voices or perspectives can be heard? (Max. 800 characters.)', max_length=800, verbose_name='How will you engage different perspectives in dialogue around the societal challenge that you aim to tackle?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='pitch',
            field=models.TextField(help_text='Share a concise and appealing text that summarizes your idea, makes the reader want to learn more and that is memorable. Summarize the challenge you are tackling, your objective, target group and approach in 3-5 sentences. This section will be published in the idea space. (Max. 500 characters.)', max_length=500, verbose_name='Idea pitch'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='plan',
            field=models.TextField(help_text='Please describe the activities, specific steps, methods and approach you will undertake to implement your project. This section will be published in the idea space. (Max. 1400 characters.)', max_length=1400, verbose_name='What is your action plan and how do you plan to get there?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='reach_out',
            field=models.TextField(help_text='What actions, measures or (communication) channels will you use to reach out to your key target groups and others to whom your project is relevant? (Max. 400 characters.)', max_length=400, verbose_name='How will you reach out to others?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='results',
            field=models.TextField(help_text='At the end of your project phase, what will have changed for the better thanks to it? This section will be published in the idea space. (Max. 800 characters.)', max_length=800, verbose_name='What are the expected results?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Here you can add a short explanation of your title, for instance: “Fostering a culture of democratic dialogue and co-designing a vision for the development of a small island.”. This section will be published in the idea space. (Max. 200 characters.)', max_length=200, verbose_name='Idea subtitle'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='sustainability',
            field=models.TextField(help_text='What seeds will you plant in order to ensure that your initiative continues beyond the project funding and that you make an impact? Try to be as specific and as realistic as possible. (Max. 800 characters.)', max_length=800, verbose_name='How do you envision the sustainability of your initiative?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='target_group',
            field=models.TextField(help_text='Please describe the key target groups that you want to reach with your project. Try to add some key figures about the groups you will be working with. This section will be published in the idea space. (Max. 800 characters.)', max_length=800, verbose_name='Who are you doing it for?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(help_text='Give your idea a short and meaningful title, for instance: “Islands of Hope”. This section will be published in the idea space. (Max. 50 characters.)', max_length=50, verbose_name='Idea title'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='total_budget',
            field=models.IntegerField(help_text='Please indicate your overall budget. The total budget may (but does not have to) include the applicant’s own contribution and/or external sources of funding. This section will be published in the idea space.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total budget'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='uniqueness',
            field=models.TextField(blank=True, help_text='Please describe what niche your initiative is filling in the specific region and context you are describing above. (Max. 800 characters.)', max_length=800, verbose_name='What makes your idea stand apart in its local and regional dimension?'),
        ),
    ]
