# Generated by Django 2.2.17 on 2021-01-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_europe_ideas', '0017_wording_changes_helptexts_and_remove_defaults_for_perspective_and_cohesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_1_details',
            field=models.TextField(blank=True, help_text='Please describe main goals, vision and activities of the organization. Please also mention the organization status (NGO, public institution, enterprise, etc.). Any organization status is possible for partners. (Max. 400 characters.)', max_length=400, verbose_name='Partner organization details'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_1_role',
            field=models.TextField(blank=True, help_text='Why did you choose this partner and how will your partner support you? (Max. 400 characters.)', max_length=400, verbose_name='Please describe the role of your partner in your project'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_2_details',
            field=models.TextField(blank=True, help_text='Please describe main goals, vision and activities of the organization. Please also mention the organization status (NGO, public institution, enterprise, etc.). Any organization status is possible for partners. (Max. 400 characters.)', max_length=400, verbose_name='Partner organization details'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_2_role',
            field=models.TextField(blank=True, help_text='Why did you choose this partner and how will your partner support you? (Max. 400 characters.)', max_length=400, verbose_name='Please describe the role of your partner in your project'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_3_details',
            field=models.TextField(blank=True, help_text='Please describe main goals, vision and activities of the organization. Please also mention the organization status (NGO, public institution, enterprise, etc.). Any organization status is possible for partners. (Max. 400 characters.)', max_length=400, verbose_name='Partner organization details'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_3_role',
            field=models.TextField(blank=True, help_text='Why did you choose this partner and how will your partner support you? (Max. 400 characters.)', max_length=400, verbose_name='Please describe the role of your partner in your project'),
        ),
    ]
