# Generated by Django 2.2.7 on 2020-01-08 16:29

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms_snippets', '0001_initial'),
        ('cms_blog', '0001_initial'),
        ('cms_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='cms_snippets.Category'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='The Image that is shown on the blog page and the blog index page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms_images.CustomImage', verbose_name='Blog Image'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='featured_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms_blog.BlogPage'),
        ),
    ]
