# Generated by Django 2.2.10 on 2020-03-09 12:36

import adhocracy4.images.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_europe_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_avatar',
            field=adhocracy4.images.fields.ConfiguredImageField('avatar', blank=True, help_text='Please upload a picture in landscape format, at least 340x340 px. You can upload a .jpg, .png or .gif.', upload_to='users/images', verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 60 characters or less. Letters, digits, spaces and @/./+/-/_ only.', max_length=75, unique=True, validators=[django.core.validators.RegexValidator('^[\\w]+[ \\w.@+\\-]*$', 'Enter a valid username. This value may contain only letters, digits, spaces and @/./+/-/_ characters. It must start with a digit or a letter.', 'invalid')], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, help_text='Please add either https:// or http:// at the beginning of your URL.', verbose_name='Website'),
        ),
    ]
