# Generated by Django 2.2.11 on 2020-03-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civic_europe_users', '0002_changed_help_text_of_avatar_username_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='europe',
        ),
    ]
