# Generated by Django 2.2.14 on 2020-12-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civic_europe_users', '0003_remove_user_europe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='get_newsletters',
        ),
    ]
