# Generated by Django 2.2.7 on 2020-01-08 16:29

import cms.home.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Header Title')),
                ('title_de', models.CharField(blank=True, max_length=255, verbose_name='Header Title')),
                ('description_en', models.TextField(blank=True)),
                ('description_de', models.TextField(blank=True, null=True)),
                ('body_en', wagtail.core.fields.StreamField([('columns', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(length=256, required=False)), ('col1', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock(length=256, required=True)), ('text', wagtail.core.blocks.TextBlock(required=True)), ('link', wagtail.core.blocks.PageChooserBlock(required=False)), ('externlink', wagtail.core.blocks.URLBlock(help_text='The external link overwrites the link to a local page. It also requires a link text.', label='External Link', required=False)), ('link_text', wagtail.core.blocks.CharBlock(help_text='Text to be displayed on the link-button.Should be quite short! If not given, the title of the linked page will be used.', required=False))], required=True)), ('col2', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock(length=256, required=True)), ('text', wagtail.core.blocks.TextBlock(required=True)), ('link', wagtail.core.blocks.PageChooserBlock(required=False)), ('externlink', wagtail.core.blocks.URLBlock(help_text='The external link overwrites the link to a local page. It also requires a link text.', label='External Link', required=False)), ('link_text', wagtail.core.blocks.CharBlock(help_text='Text to be displayed on the link-button.Should be quite short! If not given, the title of the linked page will be used.', required=False))], required=True)), ('col3', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock(length=256, required=True)), ('text', wagtail.core.blocks.TextBlock(required=True)), ('link', wagtail.core.blocks.PageChooserBlock(required=False)), ('externlink', wagtail.core.blocks.URLBlock(help_text='The external link overwrites the link to a local page. It also requires a link text.', label='External Link', required=False)), ('link_text', wagtail.core.blocks.CharBlock(help_text='Text to be displayed on the link-button.Should be quite short! If not given, the title of the linked page will be used.', required=False))], required=True))])), ('call_to_action', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock(required=True)), ('link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(required=True)), ('link_text', wagtail.core.blocks.CharBlock(required=True))], required=True)), ('text', wagtail.core.blocks.TextBlock(required=True))])), ('idea_carousel', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock(required=False)), ('year', cms.home.blocks.ProjectChooserBlock(required=False)), ('topic', wagtail.core.blocks.ChoiceBlock(choices=[('democracy_participation', 'Democracy and participation'), ('arts_cultural_activities', 'Arts and cultural activities'), ('environment', 'Environment'), ('social_inclusion', 'Social inclusion'), ('migration', 'Migration'), ('communities', 'Communities'), ('urban_development', 'Urban development'), ('education', 'Education')], required=False)), ('ordering', wagtail.core.blocks.ChoiceBlock(choices=[('newest', 'Most Recent'), ('comments', 'Most Comments'), ('support', 'Most Support'), ('title', 'Alphabetical')], required=False)), ('status', wagtail.core.blocks.ChoiceBlock(choices=[('idea_sketch', 'Idea Sketch'), ('community_award', 'Community Award Winner'), ('shortlist', 'Shortlist'), ('proposal', 'Proposal'), ('winner', 'Winner')], required=False))])), ('blogs', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Heading to show above the blog entries', required=False)), ('link', wagtail.core.blocks.PageChooserBlock(help_text='Link to blog overview', required=False))])), ('three_images_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('image_left', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('link', wagtail.core.blocks.URLBlock(required=False))], required=False)), ('image_middle', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('link', wagtail.core.blocks.URLBlock(required=False))], required=False)), ('image_right', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('link', wagtail.core.blocks.URLBlock(required=False))], required=False))]))], null=True)),
                ('body_de', wagtail.core.fields.StreamField([('columns', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(length=256, required=False)), ('col1', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock(length=256, required=True)), ('text', wagtail.core.blocks.TextBlock(required=True)), ('link', wagtail.core.blocks.PageChooserBlock(required=False)), ('externlink', wagtail.core.blocks.URLBlock(help_text='The external link overwrites the link to a local page. It also requires a link text.', label='External Link', required=False)), ('link_text', wagtail.core.blocks.CharBlock(help_text='Text to be displayed on the link-button.Should be quite short! If not given, the title of the linked page will be used.', required=False))], required=True)), ('col2', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock(length=256, required=True)), ('text', wagtail.core.blocks.TextBlock(required=True)), ('link', wagtail.core.blocks.PageChooserBlock(required=False)), ('externlink', wagtail.core.blocks.URLBlock(help_text='The external link overwrites the link to a local page. It also requires a link text.', label='External Link', required=False)), ('link_text', wagtail.core.blocks.CharBlock(help_text='Text to be displayed on the link-button.Should be quite short! If not given, the title of the linked page will be used.', required=False))], required=True)), ('col3', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock(length=256, required=True)), ('text', wagtail.core.blocks.TextBlock(required=True)), ('link', wagtail.core.blocks.PageChooserBlock(required=False)), ('externlink', wagtail.core.blocks.URLBlock(help_text='The external link overwrites the link to a local page. It also requires a link text.', label='External Link', required=False)), ('link_text', wagtail.core.blocks.CharBlock(help_text='Text to be displayed on the link-button.Should be quite short! If not given, the title of the linked page will be used.', required=False))], required=True))])), ('call_to_action', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock(required=True)), ('link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(required=True)), ('link_text', wagtail.core.blocks.CharBlock(required=True))], required=True)), ('text', wagtail.core.blocks.TextBlock(required=True))])), ('idea_carousel', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock(required=False)), ('year', cms.home.blocks.ProjectChooserBlock(required=False)), ('topic', wagtail.core.blocks.ChoiceBlock(choices=[('democracy_participation', 'Democracy and participation'), ('arts_cultural_activities', 'Arts and cultural activities'), ('environment', 'Environment'), ('social_inclusion', 'Social inclusion'), ('migration', 'Migration'), ('communities', 'Communities'), ('urban_development', 'Urban development'), ('education', 'Education')], required=False)), ('ordering', wagtail.core.blocks.ChoiceBlock(choices=[('newest', 'Most Recent'), ('comments', 'Most Comments'), ('support', 'Most Support'), ('title', 'Alphabetical')], required=False)), ('status', wagtail.core.blocks.ChoiceBlock(choices=[('idea_sketch', 'Idea Sketch'), ('community_award', 'Community Award Winner'), ('shortlist', 'Shortlist'), ('proposal', 'Proposal'), ('winner', 'Winner')], required=False))])), ('blogs', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Heading to show above the blog entries', required=False)), ('link', wagtail.core.blocks.PageChooserBlock(help_text='Link to blog overview', required=False))])), ('three_images_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('image_left', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('link', wagtail.core.blocks.URLBlock(required=False))], required=False)), ('image_middle', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('link', wagtail.core.blocks.URLBlock(required=False))], required=False)), ('image_right', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('link', wagtail.core.blocks.URLBlock(required=False))], required=False))]))], blank=True, null=True)),
                ('videoplayer_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('video_button_text_de', models.CharField(blank=True, default='Video abspielen', max_length=100)),
                ('video_button_text_en', models.CharField(blank=True, default='Play Video', max_length=100)),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('website_link_text_de', models.CharField(blank=True, default='mehr', max_length=100)),
                ('website_link_text_en', models.CharField(blank=True, default='more', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SimplePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title')),
                ('title_de', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('body_en', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('FAQs', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('faqs', wagtail.core.blocks.ListBlock(cms.home.blocks.QuestionAnswerBlock))]))], null=True)),
                ('body_de', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('FAQs', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('faqs', wagtail.core.blocks.ListBlock(cms.home.blocks.QuestionAnswerBlock))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StructuredTextPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title')),
                ('title_de', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('body_en', wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Section Title')), ('content', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.RichTextBlock(required=False)), ('FAQ', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('faqs', wagtail.core.blocks.ListBlock(cms.home.blocks.QuestionAnswerBlock))], required=False))]))]))], null=True)),
                ('body_de', wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Section Title')), ('content', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.RichTextBlock(required=False)), ('FAQ', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('faqs', wagtail.core.blocks.ListBlock(cms.home.blocks.QuestionAnswerBlock))], required=False))]))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
