# Generated by Django 2.2.8 on 2020-01-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_home', '0003_create_homepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body_en',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='description_en',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='title_en',
            new_name='translated_title',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='video_button_text_en',
            new_name='video_button_text',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='website_link_text_en',
            new_name='website_link_text',
        ),
        migrations.RenameField(
            model_name='simplepage',
            old_name='body_en',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='simplepage',
            old_name='title_en',
            new_name='translated_title',
        ),
        migrations.RenameField(
            model_name='structuredtextpage',
            old_name='body_en',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='structuredtextpage',
            old_name='title_en',
            new_name='translated_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body_de',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='video_button_text_de',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='website_link_text_de',
        ),
        migrations.RemoveField(
            model_name='simplepage',
            name='body_de',
        ),
        migrations.RemoveField(
            model_name='simplepage',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='structuredtextpage',
            name='body_de',
        ),
        migrations.RemoveField(
            model_name='structuredtextpage',
            name='title_de',
        ),
    ]
