# Generated by Django 2.2.8 on 2020-01-13 13:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms_snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigationmenuitem',
            old_name='menu_title_en',
            new_name='menu_title',
        ),
        migrations.RemoveField(
            model_name='navigationmenuitem',
            name='menu_title_de',
        ),
        migrations.AlterField(
            model_name='navigationmenuitem',
            name='subpages',
            field=wagtail.core.fields.StreamField([('link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.PageChooserBlock(required=True)), ('link_text', wagtail.core.blocks.CharBlock(required=True))]))], blank=True, help_text='These Links will be displayed in a dropdown menu', null=True, verbose_name='Submenu'),
        ),
    ]
