# Generated by Django 2.2.9 on 2020-01-20 15:59

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('civic_europe_ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ir', 'Road to impact'), ('he', 'Heroines and heroes'), ('is', 'Impact Story'), ('id', 'Take this idea!'), ('su', 'Success'), ('fa', 'Failing forward'), ('jo', 'Join forces!'), ('an', 'Anything else?')], max_length=2)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(help_text='To add content from Vimeo, Youtube, Facebook, flickr, soundcloud or instagram just paste the url into the text.')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic_europe_ideas.Idea')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
